name: Release
on:
  push:
    tags:
      - "*"  # Trigger on push to any tag
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  packages: write

jobs:
  release-binaries:
    name: Release Go Binary for Selected Architectures
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", "amd64", "arm64"]  # Reduced to 386, amd64, and arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p build
          go build -o "build/OpenGFW-${{ matrix.goos }}-${{ matrix.goarch }}" -ldflags "-s -w" .

      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: "build/*"  # Upload all binaries in the build folder
          tag_name: ${{ github.ref }}  # Tag associated with the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
